name: CI

on:
  pull_request:
    branches:
      - main
env:
  CI: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: lynx-ubuntu-24.04-xlarge
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install
        run: |
          npm i -g corepack@latest
          corepack enable
          pnpm install
      - name: Lint
        run: |
          pnpm dprint check
      - name: Build
        run: pnpm turbo build --affected
